FROM adoptopenjdk/openjdk16:latest
WORKDIR /spring

ADD ./build/libs/demo-0.0.1-SNAPSHOT.jar /spring/demo-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java","-agentlib:jdwp=transport=dt_socket,server=y,address=*:5005,suspend=n","-jar","/spring/demo-0.0.1-SNAPSHOT.jar"]